config/routes.rb
Pandorify::Application.routes.draw do

  get "home/index"
  get "home/new"
  post "home/play"
  
  get "tiny_song/get_id"
  get "song/hot_songs"
  get "recommendation/recommended"
  post "playlist/add"
  post "playlist/create"
  post "playlist/create_and_add"
  get "playlist/play"
  get "song/play"
  
  get "party/index"
  
  get "twilio/sms"
  
  resource :facebook, :except => :create do
    get :callback, :to => :create
    get :friends
    get :users_listen_to
    get :all_users
    get :like_taste
    get :edit
  end
 

  root :to => 'home#index'

end

app/models/song.rb
require 'cgi'
class Song < ActiveRecord::Base
  has_many :listens
  belongs_to :application
  belongs_to :artist
  belongs_to :album
  has_and_belongs_to_many :playlists, :join_table => "songs_playlists"
  has_many :requestedsongs, :dependent => :destroy

  scope :song_based_on_sorted_listens_by_user_since, lambda { |time| {
        :select => "#{Song.table_name}.*, count(DISTINCT #{Facebook.table_name}.id) as user_count",
        :joins => "LEFT JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id LEFT JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id",
        :conditions => ["#{Listen.table_name}.start_time > ?", time],
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song, #{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :order => "user_count DESC, coalesce(#{Song.table_name}.popularity, 0) DESC"
  }}
  
  scope :song_based_on_sorted_listens_by_user,
        :select => "#{Song.table_name}.*, count(DISTINCT #{Facebook.table_name}.id) as user_count",
        :joins => "LEFT JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id LEFT JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id",
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song,#{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :order => "user_count DESC, coalesce(#{Song.table_name}.popularity, 0) DESC"

  scope :song_based_on_sorted_listens_by_friends, lambda { |user| {
        :select => "#{Song.table_name}.*, count(DISTINCT #{Facebook.table_name}.id) as user_count",
        :joins => "LEFT JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id LEFT JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id LEFT JOIN #{Friendship.table_name} ON #{Facebook.table_name}.id = #{Friendship.table_name}.friend_id AND #{Friendship.table_name}.user_id = #{user.id}",
        :conditions => ["#{Friendship.table_name}.user_id = ?", user.id],
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song,#{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :order => "user_count DESC, coalesce(#{Song.table_name}.popularity, 0) DESC"
  }}

  #first id is user and second one is time we want for after that
  scope :song_based_on_sorted_listens_by_friends_after, lambda { |*args| {
        :select => "#{Song.table_name}.*, count(DISTINCT #{Facebook.table_name}.id) as user_count",
        :joins => "LEFT JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id LEFT JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id LEFT JOIN #{Friendship.table_name} ON #{Facebook.table_name}.id = #{Friendship.table_name}.friend_id AND #{Friendship.table_name}.user_id = #{args.first.id}",
        :conditions => ["#{Friendship.table_name}.user_id = ? AND start_time > ?", args.first.id, args.second],
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song,#{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :order => "user_count DESC, coalesce(#{Song.table_name}.popularity, 0) DESC"
  }}
  
  scope :common_songs, lambda { |*args| {
        :select => "#{Song.table_name}.*",
        :joins => "JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id AND (#{Facebook.table_name}.id = #{args.first.id} OR #{Facebook.table_name}.id = #{args.second.id})",
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song,#{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :having => "count(DISTINCT #{Facebook.table_name}.id) > 1",
        :order => "coalesce(#{Song.table_name}.popularity, 0) DESC"
  }}

  # sample user_string: (#{Facebook.table_name}.id = #{args.first.id} OR #{Facebook.table_name}.id = #{args.second.id})
  scope :sort_based_on_common_song_count, lambda { |users_string| {
        :select => "#{Song.table_name}.*, count(DISTINCT #{Facebook.table_name}.id) as user_count",
        :joins => "JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id AND #{users_string}",
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song,#{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :order => "user_count DESC, count(DISTINCT #{Listen.table_name}.id) DESC, coalesce(#{Song.table_name}.popularity, 0) DESC"
  }}

  scope :not_common_songs, lambda { |*args| {
        :select => "#{Song.table_name}.*",
        :joins => "JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id AND (#{Facebook.table_name}.id = #{args.first.id} OR #{Facebook.table_name}.id = #{args.second.id})",
        :group => "#{Song.table_name}.id, #{Song.table_name}.identifier, #{Song.table_name}.title, #{Song.table_name}.url, #{Song.table_name}.created_at, #{Song.table_name}.updated_at, #{Song.table_name}.application_id, #{Song.table_name}.popularity, #{Song.table_name}.artist_id, #{Song.table_name}.album_id, #{Song.table_name}.tiny_song,#{Song.table_name}.duration, #{Song.table_name}.key, #{Song.table_name}.mode, #{Song.table_name}.time_signature, #{Song.table_name}.duration, #{Song.table_name}.loudness, #{Song.table_name}.energy, #{Song.table_name}.tempo, #{Song.table_name}.danceability, #{Song.table_name}.echo_nested, #{Song.table_name}.last_echo_nested",
        :having => "count(DISTINCT #{Facebook.table_name}.id) = 1",
        :order => "coalesce(#{Song.table_name}.popularity, 0) DESC"
  }}
    
  scope :song_based_on_sorted_listens_for_user, lambda { |user| {
        :select => "#{Song.table_name}.*, count(#{Listen.table_name}.id) as listen_count",
        :joins => "JOIN #{Listen.table_name} ON #{Song.table_name}.id = #{Listen.table_name}.song_id JOIN #{Facebook.table_name} ON #{Listen.table_name}.facebook_id = #{Facebook.table_name}.id AND #{Facebook.table_name}.id = #{user.id}",

app/controllers/song_controller.rb
class SongController < ApplicationController
  include ApplicationHelper

  def hot_songs
    @page =  params[:page] || 1
    @after = params[:after] || 1.days.ago.utc
    @type = params[:type] || "grid"
    @tempo_min = params[:tempo_min] || 0.0
    @tempo_max = params[:tempo_max] || 300.0
    @danceability_min = params[:danceability_min] || 0.0
    @danceability_max = params[:danceability_max] || 1.0
    @energy_min = params[:energy_min] || 0.0
    @energy_max = params[:energy_max] || 1.0
    @loudness_min = params[:loudness_min] || -100.0
    @loudness_max = params[:loudness_max] || 1.0
    @from_friends = params[:from_friends] || str_to_bool(params[:from_friends]) || false
    if @from_friends
      @user = current_user || Facebook.find_by_email(params[:user_email])
      @songs = Song.song_based_on_sorted_listens_by_friends_after(@user,@after).songs_with_tempo_range(@tempo_min,@tempo_max).songs_with_danceability_range(@danceability_min,@danceability_max).songs_with_energy_range(@energy_min,@energy_max).songs_with_loudness_range(@loudness_min,@loudness_max).paginate(:page => @page )
    else
      @songs = Song.song_based_on_sorted_listens_by_user_since(@after).songs_with_tempo_range(@tempo_min,@tempo_max).songs_with_danceability_range(@danceability_min,@danceability_max).songs_with_energy_range(@energy_min,@energy_max).songs_with_loudness_range(@loudness_min,@loudness_max).paginate(:page => @page )
    end
    respond_to do |format|
       format.js
       format.json{
         render :json => @songs.to_json
       }
    end
  end
  
  def play
    obj = Song.find(params[:id])
    if obj.tiny_song == nil
      c = Curl::Easy.perform("http://tinysong.com/b/#{CGI.escape(obj.title.to_s + ' ' + obj.artist.name.to_s)}?format=json&key=96a8868b78efe9fdc0c23393f8ef6651") # FROM Tinysong
      parsed_json = ActiveSupport::JSON.decode(c.body_str)
      @id = parsed_json['SongID'].to_s if parsed_json['SongID'].to_s.size != 0
      obj.tiny_song = @id
      obj.save!
    else
      @id = obj.tiny_song
    end
    pl = current_user.playlists.find_by_name("Queue")
    pl.songs << obj
    pl.save!
    respond_to do |format|
       format.js
    end
  end
      
end

app/helpers/song_helper.rb
module SongHelper
end

app/views/song/_songs.html.erb
<% appended = false if local_assigns[:appended].nil? %>
<% if type=='grid' %>
  <% if !appended %>
  <div class="grid">
  <%end%>
  <% songs.each do |obj|%>
  <div class="grid-space">
    <div class="grid-item">
      <div class="album">
        <img class="cover" src="<%= obj.album.cover_pic_url if obj.album!=nil and obj.album.cover_pic_url!=nil %>" />
        <%= link_to "", song_play_path + "?id=#{obj.id}", :method => :get, :remote => true, :class => "play" %>
        <a href="#" class="add" id="<%= obj.id %>"></a>
        <div id="my-popover" style="display:none">
          <div class="header">
          </div>
          <ul class="content" id="<%= obj.id %>content_for_popup">
            <li>
              <a href=<%= obj.url %> >Open in Spotify! </a>
            </li>
            <% playlists = current_user.playlists %>
            <% playlists.each do |pl|%>
            <li>
              <%= link_to content_tag(:span, nil, :class=>'icon') + 'Add to ' + pl.name, playlist_add_path + "?plid=#{pl.id}&sid=#{obj.id}", :method => :post, :remote => true %>
            </li>
            <% end %>
          </ul>
        </div>

      </div>
      <div class="info">
        <p class="song bold"><%= obj.title %></p>
        <p class="artist"><%= obj.artist.name if obj.artist!=nil and obj.artist.name != nil%></p>
        <% count = 0 %>
        <% Facebook.users_listen_to(obj).each do |o| %>
        <%  count += 1 %>
        <% end %>
        <% name = Facebook.users_listen_to(obj)[rand(count)].try(:name) %>
        <p class="listens"><span class="icon love"></span><%= name %> <span class="count">(<%= rand(100) %>)</span></p>
        <p class="listens"><span class="icon headphones"></span><%= count-1 %> friends</p>
      </div>
    </div>
  </div>
  <% end %>
  <% if !appended %>
</div>
<%end%>
<%else%>
<% if !appended %>
<ul class="list-container">
<%end%>
<% songs.each do |obj|%>
<li class="row">
  <div class="actions">
    <%= link_to "", song_play_path + "?id=#{obj.id}", :method => :get, :remote => true, :class => "play" %>
    <a href="#" class="add" id="<%= obj.id %>"></a>
  </div>
  <div class="dynamic">
    <div class="song"><%= obj.title %></div>
    <div class="artist"><%= obj.artist.name if obj.artist!=nil and obj.artist.name!=nil %></div>
    <div class="album"><%= obj.album.name if obj.album!=nil and obj.album.name != nil %></div>
  </div>
  <div class="static">
    <div class="friends">
      <ul class="thumbs">
        <% friends = Facebook.users_listen_to(obj) %>
        <% count = 0 %>
        <% friends.each do |fri| %>
        <li id="<%= fri.id %>">
          <a href="/profile"><img src="<%=fri.pic_url %>?type=square" /></a>
          <div class="popover">
            <div class="triangle"></div>
            <div class="content" id="<%= fri.id %>content_for_popup">
              <img src="<%=fri.pic_url %>?type=large" />
              <p><%= fri.name %></p>
              <p class="count">133 listens</p>
            </div>
          </div>
        </li>
        <% count += 1%>
        <% break if count == 10%>
        <% end %>
      </ul>
    </div>
  </div>
</li>
<% end %>
<% if !appended %>
</ul>
<% end %>
<%end%>
<script>
$('.album img').load(function() {
  $(this).parent().addClass('loaded');
});
$('a.add').each(function(index){
  var id = $(this).attr('id');
  $(this).popover({header: '', content: '#'+id+'content_for_popup'});
});
</script>

app/views/song/hot_songs.js.erb
<% if @page == 1 %>
$('#song_view').html("<%= escape_javascript(render 'song/songs', :songs => @songs, :type =>@type, :appended => false) %>").append('<div class="loading-spinner mini"></div>');
<% else %>
$('#song_view').children(":first").append("<%= escape_javascript(render 'song/songs', :songs => @songs, :type =>@type, :appended => true) %>");
<% end %>	
$('body').removeClass('loading appending');
$('#song_view').attr("type","<%=@type%>");
$('#song_view').attr("content",'hot');
$('#song_view').attr("content_id","");
nextPage = parseInt('<%= @page %>')+1;
beforeTime = '<%= @before %>';
view_type = '<%=@type%>';
$(document).unbind('scroll', unlimited_scroll);
$(document).endlessScroll({
  bottomPixels: 400,
  fireOnce: true,
  fireDelay: 500,
  ceaseFire: function(){
    return $('#cease_fire_on_scroll').attr('value') == 'true';
  },
  callback: function(){
    $(document).unbind('scroll', unlimited_scroll);
    $.get("<%= song_hot_songs_path %>", { type: view_type, page: nextPage, before: beforeTime } );
    $('body').addClass('appending');
  }
});

$(".slide-out-div").css("display","none");

app/views/song/party.js.erb
<% if @page == 1 %>
$('#song_view').html("<%= escape_javascript(render 'song/songs', :songs => @songs, :type =>@type, :appended => false) %>").append('<div class="loading-spinner mini"></div>');
<% else %>
$('#song_view').children(":first").append("<%= escape_javascript(render 'song/songs', :songs => @songs, :type =>@type, :appended => true) %>");
<% end %>	
$('#song_view').attr("type","<%=@type%>");
$('#song_view').attr("content",'hot');
$('#song_view').attr("content_id","");
$('body').removeClass('loading');
nextPage = parseInt('<%= @page %>')+1;
beforeTime = '<%= @before %>';
view_type = '<%=@type%>';
$(document).unbind('scroll', unlimited_scroll);
$(document).endlessScroll({
  bottomPixels: 400,
  fireOnce: true,
  fireDelay: 500,
  ceaseFire: function(){
    return $('#cease_fire_on_scroll').attr('value') == 'true';
  },
  callback: function(){
    $(document).unbind('scroll', unlimited_scroll);
    $.get("<%= song_hot_songs_path %>", { type: view_type, page: nextPage, before: beforeTime } );
    $('body').addClass('appending');
  }
});

app/views/song/play.js.erb
$("#player object").remove();
$("#player").append('<object width="250" height="40" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="gsSong'+<%= @id %>+'" name="gsSong'+<%= @id %>+'"><param name="movie" value="http://grooveshark.com/songWidget.swf" /><param name="wmode" value="window" /><param name="allowScriptAccess" value="always" /><param name="flashvars" value="hostname=cowbell.grooveshark.com&songIDs='+<%= @id %>+'&style=metal&p=1" /><!--[if !IE]>--><object type="application/x-shockwave-flash" data="http://grooveshark.com/songWidget.swf" width="250" height="40"><param name="wmode" value="window" /><param name="allowScriptAccess" value="always" /><param name="flashvars" value="hostname=cowbell.grooveshark.com&songIDs='+<%= @id %>+'&style=metal&p=1" /></object><!--<![endif]--></object>');

$("#player img").attr('src', 'http://o.scdn.co/image/f153d9201208842ef7f8d37dc8af2f33b84a9ce0');
$("#player .song").text(<%= rand(9999999999) %>);
$("#player .artist").text(<%= rand(9999999999999999) %>);
$("#player .current_playlist").attr('href', $('.playlist.active_playlist a').attr('href')).removeClass('disabled');