config/routes.rb
Pandorify::Application.routes.draw do

  get "home/index"
  get "home/new"
  post "home/play"
  
  get "tiny_song/get_id"
  get "song/hot_songs"
  get "recommendation/recommended"
  post "playlist/add"
  post "playlist/create"
  post "playlist/create_and_add"
  get "playlist/play"
  get "song/play"
  
  get "party/index"
  
  get "twilio/sms"
  
  resource :facebook, :except => :create do
    get :callback, :to => :create
    get :friends
    get :users_listen_to
    get :all_users
    get :like_taste
    get :edit
  end
 

  root :to => 'home#index'

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :songs
  
  def update_album_cover
    c = Curl::Easy.perform(self.url)
    tag = c.body_str.match /<img id=\"cover-art\" src=\".*\"/
    link = tag[0][25..tag[0].size]
    link = link[0..link.size-2]
    self.cover_pic_url = link
    self.save!
    # cleaning up
    c = nil
    tag = nil
    link = nil
    GC.start # Run the garbage collector to be sure this is real !    
  end
  
  def perform
    begin
      self.update_album_cover
    rescue
      return
    end
  end
  
  class << self
    extend ActiveSupport::Memoizable
  
    def update_all_covers
      Album.find_each(:conditions => ["cover_pic_url is null"]) do |obj|
        # begin
          Delayed::Job.enqueue obj
        # rescue
          # next
        # end
      end
    end
    
    def perform
      self.update_all_covers
    end
    
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ApplicationHelper
  before_filter :require_authentication, :only => :play
  
  def index
    if authenticated?
        @user = current_user
        @playlists =  @user.playlists
        @songs = Song.song_based_on_sorted_listens_by_user_since(1.days.ago.utc).paginate(:page => @page )
      respond_to do |format|
        format.html
      end
    end
  end

  def new
    if authenticated?
      @music = current_user.retrieve_music_activity 2.days.ago
    end    
  end
  
  #POST home/play
  def play
    identifiers = params[:friend_tokens].split(",")
    friend_list = current_user.friends.reject {|item| !identifiers.include? item.identifier}
    common_artist = Hash.new
    friend_list.each do |friend|
      user = FbGraph::User.fetch(friend.identifier, :access_token => friend.access_token)
      user.retrieve_music.each do |music|
        #if music.category == "Musician/band"
          if common_artist.has_key? music.name
            common_artist[music.name] += 1
          else
            common_artist[music.name] = 1
          end
        #end
      end  
    end
    
    current_user.retrieve_music.each do |music|
      #if music.category == "Musician/band"
        if common_artist.has_key? music.name
          common_artist[music.name] += 1
        else
          common_artist[music.name] = 1
        end
      #end
    end
    
    sort_common_artists  = common_artist.sort_by {|key, values| -1*values}
    
    @tracklist = Array.new  
    counter = 0
    sort_common_artists.take(30).each do |pair|
      begin
        # c = Curl::Easy.perform("http://ws.spotify.com/search/1/track.json?q=#{CGI.escape pair[0].to_s}") # FROM SPOTIFY 
        c = Curl::Easy.perform("http://tinysong.com/s/#{CGI.escape pair[0].to_s.sub(" ","+")}?format=json&limit=#{[32,2**pair[1]-1].min}&key=186bd60f3a33be26da02d62d334bddf4") # FROM Tinysong      
      rescue
        next
      end
      parsed_json = ActiveSupport::JSON.decode(c.body_str)
      # parsed_json['tracks'].each do |track| # FOR SPOTIFY
      parsed_json.each do |track| # FOR TINYSONG
        # count = 0 # FOR SPOTIFY
        check = false
        @tracklist.each do |item|
          check = (item[0].downcase == track['SongName'].downcase)
          break if check
        end
        next if check
        # @tracklist << [track['name'], "http://open.spotify.com/track/" + track['href'][14..track['href'].length]] # FOR SPOTIFY
        @tracklist << [track['SongName'], track['ArtistName'], track['Url'], track['SongID']] # FOR TINYSONG
        counter += 1
        break if counter == 30
        # count += 1 # FOR SPOTIFY
        # break if count == 2**pair[1]-1 # FOR SPOTIFY
      end
      break if counter == 30
    end

    # @tracklist.each do |track| # FOR SPOTIFY
    #     begin
    #       c = Curl::Easy.perform("http://tinysong.com/b/#{CGI.escape track[0].to_s.sub(" ","+")}?format=json&key=186bd60f3a33be26da02d62d334bddf4") # FOR SPOTIFY
    #     rescue
    #       next
    #     end
    #   parsed_json = ActiveSupport::JSON.decode(c.body_str) # FOR SPOTIFY
    #   track << parsed_json['SongID'] # FOR SPOTIFY
    # end # FOR SPOTIFY
        
    
  	respond_to do |format|
       format.html # play.html.erb
    end

  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if !authenticated? %>
<body class="tour">
  <div class="container">
    <a class="logo_dark" href="/">Jolicloud</a>
    <%= link_to "Login with Facebook", new_facebook_path, :class => "facebook button" %>
  </div>
  <% else %>
  <body class="app">
    <header>
      <div id="header-container">
        <a class="logo" href="/">soundbook</a>
        <div id="header-right-container">
          <div id="controls">
            <button class="control prev"></button>
            <button class="control play"></button>
            <button class="control next"></button>
          </div>
          <div id="player">
            <div class="album">
              <img class="cover" src="" />
            </div>
            <div class="info">
              <p class="song"></p>
              <p class="artist"></p>
            </div>
            <a href="" class="current_playlist disabled" data-method="get" data-remote="true"></a>
            <object width="250" height="40">
              <param name="movie" value="http://listen.grooveshark.com/songWidget.swf">
              <param name="wmode" value="window">
              <param name="allowScriptAccess" value="always">
              <param name="flashvars" value="hostname=cowbell.grooveshark.com&amp;widgetID=&amp;style=metal&amp;p=0">
              <embed src="http://listen.grooveshark.com/songWidget.swf" type="application/x-shockwave-flash" width="250" height="40" flashvars="hostname=cowbell.grooveshark.com&amp;widgetID=&amp;style=metal&amp;p=0" allowscriptaccess="always" wmode="window">
              </object>
            </div>
            <div class="view-toggle">
              <button class="detail">detail</button>
              <button class="grid active">grid</button>
            </div>
          </div>
        </div>
      </div>
    </header>
    <nav id = "side_bar">
      <section>
        <h3 class="lobster">apps</h3>
        <ul>
          <li class="hot active"><%= link_to content_tag(:span, nil, :class=>'icon') + "What's Hot", song_hot_songs_path, :method => :get, :remote => true %></li>
          <li class="match"><%= link_to content_tag(:span, nil, :class=>'icon') + "Taste Match", recommendation_recommended_path, :method => :get, :remote => true %></a></li>
          <!-- <li class="shuffle"><a href="#"><span class="icon"></span>Shuffle</a></li> -->
          <li class="party"><a onclick = "party()"><span class="icon"></span>Party DJ</a></a></li>
        </ul>
      </section>
      <section>
        <h3 class="lobster">playlists</h3>
        <ul>
<% @playlists.each do |pl|%>
<li class="playlist <%='queue active_playlist' if pl.perm %>"><%= link_to content_tag(:span, nil, :class=>'icon') + pl.name, playlist_play_path + "?id=#{pl.id}", :method => :get, :remote => true %><span class="delete"></span></li>
<% end %>
<li class="playlist add"><a href="#"><span class="icon"></span>Create playlist</a></li>
</ul>
</section>
<section>
  <h3 class="lobster">account</h3>
  <ul>
    <li class="profile"><%= link_to content_tag(:span, nil, :class=>'icon') + "Profile", edit_facebook_path, :method => :get, :remote => true %></a></li>
    <li class="settings"><a href="#"><span class="icon"></span>Settings</a></li>
    <li class="logout">
      <%= link_to content_tag(:span, nil, :class=>'icon') + "Logout", facebook_path, :method => :delete, :class => "logout" %>
    </li>
  </ul>
</section>
</nav>

<div id="right-pane">
      <div class="loading-spinner"></div>
      <!-- <header id="toolbar" class="joli-header" style="display: block; ">
      <nav id="menu"></nav>
      <nav id="options"></nav>
      <div data-template="joli/searchfield" class="joli-searchfield search" data-class="joli.searchfield" id="search" data-var="search">
      <input data-var="input" type="text" placeholder="Search apps and friends" data-class="joli.widget" class="input">
      <div data-var="clearinput" data-class="joli.widget" class="clearinput" style="display: none; ">
      <a data-var="clearlink" data-event="clear" data-class="joli.clickable" class="clearlink">Clear</a>
      </div>
      <ul data-item="joli/sectionchooser/section" data-template="joli/sectionchooser" class="joli-sectionchooser results" data-class="joli.sectionchooser" data-var="results" style="display: none; ">
      </ul>
      </div>
      </header> -->
      <!-- type can be grid or detail and content can be hot or recom or playlist if playlist content_id is the id of the playlist -->
    <section id = "song_view" type="grid" content="hot" content_id = "">
      <%= render "song/songs", :songs => @songs, :type =>'grid' %>
    </section>
    <% end %>

app/views/home/new.html.erb
<pre>
<!-- <%= @music.to_xml.to_s %> -->
<%= @music.count %>
<% @music.each do |object| %>
	<%= object.start_time %> - <%= object.end_time %> - <%= object.publish_time %> -
	<br/> <%= object.from.name %> - <%= object.from.identifier %>
	<br/> <%= object.application.name %> -
	<br/> <%= object.type %> -
	<br/> <%= object.objects %> -
	<br/> raw = <%= object.raw_attributes %> -
	<br/> <%= object.comments %> -
	<br/> <%= object.likes %>
<br/>
<br/>
<br/>
<% end %>
</pre>

app/views/home/play.html.erb
<%song_ids = []%>
<% @tracklist.each do |track| %> 
	<% song_ids << track[3].to_s%>
<%end%>
<div id="container">
	<div id="main" style="text-align: center;">
		<object align="center" style="padding-top: 10px" width="250" height="<%= [250 + ((@tracklist.count/4)-1)*75, 600].min %>" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id="gsManySongs31673607280782744" name="gsManySongs31673607280782744">
			<param name="movie" value="http://grooveshark.com/widget.swf" />
			<param name="wmode" value="window" /><param name="allowScriptAccess" value="always" />
			<param name="flashvars" value="hostname=cowbell.grooveshark.com&songIDs=<%= song_ids.join(',') %>&bbg=4a8f2c&bth=4a8f2c&pfg=4a8f2c&lfg=4a8f2c&bt=FFFFFF&pbg=FFFFFF&pfgh=FFFFFF&si=FFFFFF&lbg=FFFFFF&lfgh=FFFFFF&sb=FFFFFF&bfg=666666&pbgh=666666&lbgh=666666&sbh=666666&p=0" />
			<!--[if !IE]>-->
			<object type="application/x-shockwave-flash" data="http://grooveshark.com/widget.swf" width="250" height="<%= [250 + ((@tracklist.count/4)-1)*75, 600].min %>">
				<param name="wmode" value="window" /><param name="allowScriptAccess" value="always" /><param name="flashvars" value="hostname=cowbell.grooveshark.com&songIDs=<%= song_ids.join(',') %>&bbg=4a8f2c&bth=4a8f2c&pfg=4a8f2c&lfg=4a8f2c&bt=FFFFFF&pbg=FFFFFF&pfgh=FFFFFF&si=FFFFFF&lbg=FFFFFF&lfgh=FFFFFF&sb=FFFFFF&bfg=666666&pbgh=666666&lbgh=666666&sbh=666666&p=0" />
				</object>
				<!--<![endif]-->
				</object>

<br />
<br />
<br />

<hr style="border: none; border-bottom-color: rgba(0, 0, 0, 0.1); box-shadow: 0 1px 0 #fff;"/>
<h2>Open in <!-- Spotify -->Grooveshark!</h2>
<hr style="border: none; border-bottom-color: rgba(0, 0, 0, 0.1); box-shadow: 0 1px 0 #fff;"/>

<% @tracklist.each do |track| %> 
	<%= link_to track[0].to_s + " - " + track[1].to_s, track[2].to_s, :class => 'track' %>
	<br />
<%end%>
	</div>
</div>

<%= @parsed_json.to_s %>