config/routes.rb
Pandorify::Application.routes.draw do

  get "home/index"
  get "home/new"
  post "home/play"
  
  get "tiny_song/get_id"
  get "song/hot_songs"
  get "recommendation/recommended"
  post "playlist/add"
  post "playlist/create"
  post "playlist/create_and_add"
  get "playlist/play"
  get "song/play"
  
  get "party/index"
  
  get "twilio/sms"
  
  resource :facebook, :except => :create do
    get :callback, :to => :create
    get :friends
    get :users_listen_to
    get :all_users
    get :like_taste
    get :edit
  end
 

  root :to => 'home#index'

end

app/models/party.rb
class Party < ActiveRecord::Base
  has_and_belongs_to_many :facebooks, :join_table => "facebooks_parties"
  has_many :songs, :through => :requestedsongs, :source => :song
  has_many :requestedsongs, :dependent => :destroy
  belongs_to :host, :foreign_key => :host_id, :class_name => 'Facebook'
end

app/controllers/party_controller.rb
class PartyController < ApplicationController
  include ApplicationHelper

  def index
    
    @tempo_min = params[:tempo_min] || 0.0
    @tempo_max = params[:tempo_max] || 300.0
    @danceability_min = params[:danceability_min] || 0.0
    @danceability_max = params[:danceability_max] || 1.0
    @energy_min = params[:energy_min] || 0.0
    @energy_max = params[:energy_max] || 1.0
    @loudness_min = params[:loudness_min] || -100.0
    @loudness_max = params[:loudness_max] || 1.0
    @tokens = params[:friend_tokens]

    if current_user
      @host = current_user
    elsif params[:host]
      @host = Facebook.find(params[:host])
    elsif
      @host = Facebook.find_by_email(params[:host_email])
    end
  
    ids = params[:friend_tokens].split(",")
    ids_string = "("
    i = 0
    while i < ids.size() - 1
      ids_string += "#{Facebook.table_name}.id = #{ids[i]} OR "
      i += 1
    end
    ids_string += "#{Facebook.table_name}.id = #{ids[i]})"
    @page =  params[:page] || 1
    @songs = Song.sort_based_on_common_song_count(ids_string).songs_with_tempo_range(@tempo_min,@tempo_max).songs_with_danceability_range(@danceability_min,@danceability_max).songs_with_energy_range(@energy_min,@energy_max).songs_with_loudness_range(@loudness_min,@loudness_max).paginate(:page => @page )

    @party = Party.find_or_initialize_by_host_id(@host.id);
    @party.facebooks = Facebook.find(:all,:conditions=>[ids_string])
    reqSongs = []
    Requestedsong.find(:all, :conditions => ['party_id = ? AND added is not TRUE', @party.id]).each do |request|
      reqSongs << request.song
      request.added = true
      request.save!
    end
    @party.songs = reqSongs;
    @party.save
    
      
    
    @type = params[:type] || "grid"

    respond_to do |format|
       format.js
       format.json{
         render :json => {:matched => @songs.to_json, :requested => @party.songs.to_json}
       }
    end


  end
  
end

app/helpers/parties_helper.rb
module PartiesHelper
end

app/views/party/_tokenizer.html.erb
<div id = "token-div">
<p>Add name of people in your party</p>
<input id="friend_tokens" type="text" autocomplete="off" style="outline-style: none; outline-width: initial; outline-color: initial; width: 30px; " id="token-input-demo-input-facebook-theme"></input>
</div>
<script>
$("#friend_tokens").tokenInput("/facebook/all_users.json", {
  crossDomain: false,
  //    prePopulate: $("#book_author_tokens").data("pre"),
  theme: "facebook"
});
</script>

app/views/party/index.js.erb
<% if @page == 1 %>
$('#song_view').html("<%= escape_javascript(render 'song/songs', :songs => @songs, :type => @type) %>").append('<div class="loading-spinner mini"></div>');
<% else %>
$('#song_view').children(":first").append("<%= escape_javascript(render 'song/songs', :songs => @songs, :type =>@type, :appended => true) %>");
<% end %>
$('#song_view').children(":first").append("<%= escape_javascript(render 'song/songs', :songs =>  @party.songs, :type =>@type, :appended => true) %>");	
$('#song_view').attr("type","<%=@type%>");
$('#song_view').attr("content",'hot');
$('#song_view').attr("content_id","");
$('body').removeClass('loading appending');
nextPage = parseInt('<%= @page %>')+1;
beforeTime = '<%= @before %>';
view_type = '<%=@type%>';
$(document).unbind('scroll', unlimited_scroll);
$(document).endlessScroll({
  bottomPixels: 400,
  fireOnce: true,
  fireDelay: 500,
  ceaseFire: function(){
    return $('#cease_fire_on_scroll').attr('value') == 'true';
  },
  callback: function(){
    $(document).unbind('scroll', unlimited_scroll);
    $.get("<%= party_index_path %>"+"?friend_tokens="+"<%= @tokens %>", { type: view_type, page: nextPage, before: beforeTime, tempo_min: <%= @tempo_min %>, tempo_max: <%= @tempo_max %>, danceability_min: <%= @danceability_min %>, danceability_max: <%= @danceability_max %>, energy_min: <%= @energy_min %>, energy_max: <%= @energy_max %>, loudness_min: <%= @loudness_min %>, loudness_max: <%= @loudness_max %>} );
    $('body').addClass('appending');
  }
});